#
# Executes commands at the start of an interactive session.
#
# Authors:
#   James Carr <carrgo001@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source autojump

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Source config files

for file in "${ZDOTDIR:-$HOME}/.zprezto/system/"*; do
  source "$file"
done

# Source local configs

EXTRA_DIR="$HOME/.extra/runcom"
if [ -d "$EXTRA_DIR" ]; then
  for file in "${EXTRA_DIR}/"*; do
    source "$file"
  done
fi
unset EXTRA_DIR

if command -v direnv 1>/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
